#!/bin/zsh


zshrc() {
    echo "==========================================================="
    echo "             link my zshrc                                  "
    echo "-----------------------------------------------------------"
    cat .zshrc > $HOME/.zshrc
}

# change time zone
sudo ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
sudo dpkg-reconfigure --frontend noninteractive tzdata

zshrc

# ZSH {
# Change to zsh
if [[ "$SHELL" != "$(which zsh)" ]]; then
		sudo chsh -s $(which zsh)
fi

# ln -sf "$(pwd)/.zshrc" "~/.zshrc"


function link_files() {
  if [[ ! $(pwd) -ef $HOME ]]; then
    # Git link
    rm -f ~/.gitconfig
    ln -s $(pwd)/.gitconfig ~/.gitconfig
  fi
}

echo "Symlinking dotfiles"
link_files
echo "Finish symlinking dotfiles"

# make directly highlighting readable - needs to be after zshrc line
# colors: https://askubuntu.com/questions/466198/how-do-i-change-the-color-for-directories-with-ls-in-the-console
# configuring colors: https://www.bigsoft.co.uk/blog/2008/04/11/configuring-ls_colors
echo "" >> ~/.zshrc
echo "# remove ls and directory completion highlight color" >> ~/.zshrc
echo "_ls_colors=':ow=01;33'" >> ~/.zshrc
echo 'zstyle ":completion:*:default" list-colors "${(s.:.)_ls_colors}"' >> ~/.zshrc
echo 'LS_COLORS+=$_ls_colors' >> ~/.zshrc