#!/bin/zsh


# ZSH {
# Change to zsh
if [[ "$SHELL" != "$(which zsh)" ]]; then
		sudo chsh -s $(which zsh)
fi


function link_files() {
  if [[ ! $(pwd) -ef $HOME ]]; then
    # Git link
    rm -f ~/.gitconfig
    ln -s $(pwd)/.gitconfig ~/.gitconfig
  fi
}

function setup_zsh() {
  ln -sf "$(pwd)/.zshrc" "~/.zshrc"
}

echo "Symlinking dotfiles"
link_files
echo "Finish symlinking dotfiles"

